# Copyright (C) 2025 KA-AN <andryajpeni@gmail.com>

[bar]
fill = ━
empty = ╍
indicator = 
; Nerd font :   ,  ⏽,  樂 籠 錄 , 雷 絛
 
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/vol-bar]
type = internal/pulseaudio

; Sink to be used, if it exists (find using `pacmd list-sinks`, name field)
; If not, uses default sink
sink = 

; Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
; Default: true
use-ui-max = false

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 1

; Available tags:
;   <label-volume> (default)
;   <ramp-volume>
;   <bar-volume>
format-volume = <ramp-volume>

; Available tags:
;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
format-muted = <label-muted>
format-muted-prefix = 0
format-muted-prefix-font = 6
format-muted-prefix-foreground =  #76f8ff


; Available tokens:
;   %percentage% (default)
; label-volume = %percentage%%

; Available tokens:
;   %percentage% (default
label-muted = "    "
label-muted-foreground = #76f8ff

; Only applies if <ramp-volume> is used
ramp-volume-0 = 0
ramp-volume-1 = 5
ramp-volume-2 = 10
ramp-volume-3 = 15
ramp-volume-4 = 20
ramp-volume-5 = 25
ramp-volume-6 = 30
ramp-volume-7 = 35
ramp-volume-8 = 40
ramp-volume-9 = 45
ramp-volume-10 = 50
ramp-volume-11 = 55
ramp-volume-12 = 60
ramp-volume-13 = 65
ramp-volume-14 = 70
ramp-volume-15 = 75
ramp-volume-16 = 80
ramp-volume-17 = 85
ramp-volume-18 = 90
ramp-volume-19 = 95
ramp-volume-20 = 100

ramp-volume-font = 6
ramp-volume-padding = 1
ramp-volume-foreground = #76f8ff
 
; Only applies if <bar-volume> is used
bar-volume-width = 15
bar-volume-gradient = false

bar-volume-indicator = ${bar.indicator}
bar-volume-indicator-font = 3
bar-volume-indicator-padding = 1
bar-volume-indicator-foreground = ${color.FOREGROUND}

bar-volume-fill = ${bar.fill}
bar-volume-fill-font = 3
bar-volume-fill-padding = 1
bar-volume-foreground-0 = ${color.FOREGROUND}
bar-volume-foreground-1 = ${color.FOREGROUND}
bar-volume-foreground-2 = ${color.FOREGROUND}
bar-volume-foreground-3 = ${color.FOREGROUND}
bar-volume-foreground-4 = ${color.FOREGROUND}

bar-volume-empty = ${bar.empty}
bar-volume-empty-font = 3
bar-volume-empty-padding = 1
bar-volume-empty-foreground = ${color.FOREGROUND}

; If defined, it will replace <ramp-volume> when
; headphones are plugged in to `headphone_control_numid`
; If undefined, <ramp-volume> will be used for both
; Only applies if <ramp-volume> is used
ramp-headphones-0 = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
   
[module/volume-bar]
type = internal/pulseaudio

sink =  
use-ui-max = false
interval = 5
format-volume = <bar-volume>
format-volume-offset = -1
label-muted = "   "
label-muted-foreground = #76f8ff
format-volume-font = 15
bar-volume-width = 7
bar-volume-gradient = false
bar-volume-indicator = ${bar.indicator}
bar-volume-indicator-font = 15
bar-volume-indicator-foreground =  #76f8ff
bar-volume-fill = ${bar.fill}
bar-volume-fill-font = 15
bar-volume-foreground-0 =  #76f8ff
bar-volume-foreground-1 =  #76f8ff
bar-volume-foreground-2 =  #76f8ff
bar-volume-foreground-3 =  #76f8ff
bar-volume-foreground-4 =  #76f8ff
bar-volume-empty = ${bar.empty}
bar-volume-empty-font = 15
bar-volume-empty-foreground =  #76f8ff
ramp-headphones-0 = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
  
[module/backlight-bar]
type = internal/xbacklight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = intel_backlight
 
format = <bar>
format-padding= 1
format-offset= -5
bar-width = 7
bar-gradient = false

bar-indicator = ${bar.indicator}
bar-indicator-font = 15
bar-indicator-foreground =   #76f8ff

bar-fill = ${bar.fill}
bar-fill-font = 15
bar-foreground-0 =   #76f8ff
bar-foreground-1 =   #76f8ff
bar-foreground-2 =   #76f8ff
bar-foreground-3 =   #76f8ff
bar-foreground-4 =   #76f8ff

bar-empty = ${bar.empty}
bar-empty-font = 15
bar-empty-foreground =   #76f8ff
