;; TOP-MODULE_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/vol-level]
type = custom/text
content = "AUDIO       "
content-font = 10
content-offset = -41
content-foreground = #fe6760
format-underline = true
format-underline-color = #76f8ff 
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
 
[module/backlight]
type = internal/xbacklight 
card = intel_backlight
format = <ramp>
content-foreground = #fe6760
format-underline = true
format-underline-color = #76f8ff 
ramp-0 = 0
ramp-1 = 5
ramp-2 = 15
ramp-3 = 20
ramp-4 = 30
ramp-5 = 35
ramp-6 = 45
ramp-7 = 50
ramp-8 = 60
ramp-9 = 65
ramp-10 = 75
ramp-11 = 80
ramp-12 = 90
ramp-13 = 95
ramp-14 = 100
ramp-font = 6
ramp-foreground = #27ef99
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/br-level]
type = custom/text
content = " BRIGHTNESS"
content-font = 10
content-offset = -51
content-foreground = #fe6760
format-underline = true
format-underline-color = #76f8ff 
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
inline-mode = false
enable-click = true
enable-scroll = true
reverse-scroll = true
fuzzy-match = true
ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-default = 0
format = <label-state>
label-monitor = %name%
label-focused = %name%
label-focused-foreground = #76f8ff
; label-focused-underline = #76f8ff
label-focused-padding = 1
label-focused-font = 12
label-occupied = %name%
label-occupied-foreground = ${color.COLOR_Y}
; label-occupied-underline = ${color.COLOR_Y}
label-occupied-padding = 2
label-occupied-font = 9
label-urgent = %name%
label-urgent-foreground = ${color.COLOR_G}
; label-urgent-underline = ${color.COLOR_G}
label-urgent-padding = 2
label-urgent-font = 9
label-empty = %name%
label-empty-foreground = ${color.FOREGROUND}
; label-empty-underline = ${color.ACCENT}
label-empty-padding = 2
label-empty-font = 14
label-separator = " "
label-separator-padding = 0
label-separator-foreground = ${color.ALTBACKGROUND}
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
 
[module/cpu]
type = internal/cpu
interval = 1
; format-prefix = "󱂹"
format-prefix = "󰛯"
; format-prefix = ""
format-prefix-font = 4
format-prefix-foreground = #ff6159
format = <label>
label = " %percentage%"
label-font = 12
label-foreground = #d84640
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/memory]
type = internal/memory
interval = 1
format = <label>
format-prefix = " /"
format-font = 13
format-foreground = #ea5244
label = " %mb_used%"
label-font = 13
label-foreground = #ea5244
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
   
[module/filesystem]
type = internal/fs
mount-0 = /
interval = 30
fixed-values = true
format-mounted = <label-mounted>
; format-mounted-prefix = "€$"
format-mounted-prefix = "STR"
format-mounted-font = 16
format-mounted-foreground = #edbc3b
format-unmounted = <label-unmounted>
; format-unmounted-prefix = "STR"
format-unmounted-prefix = "€$"
format-unmounted-font = 16
format-unmounted-foreground = #edbc3b
label-mounted = " %free%"
label-mounted-font = 12
label-mounted-foreground = #e95147
label-unmounted = " %mountpoint%: not mounted "
label-unmounted-font = 12
label-unmounted-foreground = #e95147
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; BOTTOM-MODULE-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/btna]
type = custom/text
content = ""
content-font = 5
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/updates]
type = custom/script
exec = ~/.config/bspwm/themes/cyberpunk2077/polybar/scripts/updates.sh
tail = true
interval = 5
format = <label>
format-padding = 18
format-prefix = 
label = %output%
click-left = ~/.config/bspwm/scripts/rofi_update.sh
click-right = exo-open --launch TerminalEmulator && sleep 0.6 && xdotool type 'sudo pacman -Syu'
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/skull]
type = custom/script
exec = /home/mrnngstr666/.config/bspwm/themes/cyberpunk2077/polybar/scripts/spinner.sh
interval = 0
tail = true
; format = <label> 
; format-offset = -7
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/cpu-usages]
type = custom/script
exec = /home/mrnngstr666/.config/bspwm/themes/cyberpunk2077/polybar/scripts/cpu-usage.sh
interval = 0
tail = true
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/zero-binnary]
type = custom/script
exec = /home/mrnngstr666/.config/bspwm/themes/cyberpunk2077/polybar/scripts/zerobin.sh
interval = 0
tail = true
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; EXTRA-MODULE_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/net]
type = custom/script
exec = /home/mrnngstr666/.config/bspwm/themes/cyberpunk2077/polybar/scripts/scroll-binnary.sh
interval = 0
tail = true
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
 
[module/date]
type = internal/date
interval = 1.0
time = "  %I:%M %p"
time-alt = "  %a, %d %b %Y"
format = <label> 
label = %time%
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/xwindow]
type = internal/xwindow
format = <label>
label = "%class%  "
label-font = 7
format-offset = -210
label-foreground = ${color.FOREGROUND}
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/menu]
type = custom/text
content = " "
content-prefix = ﮊ
content-prefix-font = 2
content-foreground = ${color.FOREGROUND}
content-padding = 0
click-left = ~/.config/bspwm/scripts/rofi_launcher
click-right = ~/.config/bspwm/scripts/rofi_runner
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sysmenu]
type = custom/text
content = ""
content-foreground = ${color.FOREGROUND}
content-padding = 0
click-left = ~/.config/bspwm/scripts/rofi_powermenu
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
 
[module/net-indicator]
type = custom/script
exec = /home/mrnngstr666/.config/bspwm/themes/cyberpunk2077/polybar/scripts/net-indicator.sh
interval = 0
tail = true
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/checknet]
type = custom/script
exec = ~/.config/bspwm/themes/cyberpunk2077/polybar/scripts/check-network
tail = true
interval = 5
format = <label>  
format-font = 10
label = %output%
click-left = nmd &
click-right = nmd &
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; DECOR-MODULE_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/separt]
type = custom/text
content = " " 
content-foreground = transparent
format-underline = true
format-underline-color = #76f8ff 
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

